### ISSUE TITLE
Create a plan for shepherding

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#114]
Depends on #102 and #103

**Comment by PeterJCLaw** [comment]
@mildlyincompetent do you have someone lined up to manage shepherding at the competition? Organising the shepherds so things run smoothly is non-trivial, so they're going to want to know what they're doing with a reasonable amount of notice.

**Comment by trickeydan** [comment]
> @mildlyincompetent do you have someone lined up to manage shepherding at the competition? Organising the shepherds so things run smoothly is non-trivial, so they're going to want to know what they're doing with a reasonable amount of notice.

None of the roles have been assigned yet

**Comment by sedders123** [comment]
> @mildlyincompetent do you have someone lined up to manage shepherding at the competition? 

I have done this at SmallPiece and Sourcebots (admittedly a much smaller scale) but am happy to volunteer for this if it would be useful

**Comment by PeterJCLaw** [comment]
There's a bunch of documentation about shepherding at https://github.com/thomasleese/sr-match-coordinator/wiki/Shepherding, and (while I've not been a shepherd) I've outlined an overview plus some other thoughts below in case they're useful.

The venue is divided into zones, with a shepherd in each. Zones are generally a dozen or so teams. I assume that this is aimed to be enough that we don't need a shepherd for each team, while small enough that a shepherd can reasonably learn all the names quickly and speak to each of them in person before each of their matches.

The shepherds have a form of shared communication. Originally this was handheld radios, though more recently they've used slack (specifically [#shepherding](https://studentrobotics.slack.com/messages/shepherding/)).

The shepherds each have a printout of the match schedule, with the teams in their zone highlighted, usually on a clipboard. `srcomp` produces the PDFs for these (including the highlighting). This allows them to stay well ahead of the schedule without relying on the communication channel.

There is a page in the [srcomp-screens](https://github.com/PeterJCLaw/srcomp-screens) which shows which teams are expected in the staging area at what times for their matches. This is displayed as a fixed screen on a desk in the staging area. The timings of this are usually tuned lightly at the event, depending for example on the time taken for teams to reach the staging area.
There is usually one person watching this screen for the entirety of the competition, they then signal (via radio/slack) to the other shepherds which teams are needed when.
This screen is usually located in the staging area so that the people manning the staging area can also use it to determine which teams should be in which arena zones (it's colour-coded for this purpose).

There are usually two or three other shepherds manning the staging area:
 * someone at the gate ("Guard")
 * one or two people handling out and collecting ~badges~ flags and competition-mode USB sticks ("Badgers")

Other things it's worth knowing:
 * the first round of league matches (i.e: everyone's first appearance) are double-spaced, so as to allow the shepherds and teams some warm-up time (see also #103 for this year's league schedule)
 * the first round of league matches usually pull teams in the same order which their robots are inspected, to ensure that all robots have been inspected (see also #103 for this year's league schedule), which also ends up being a shortest-path walk through the venue
 * delays to the schedule can and do happen; this is fully supported -- `srcomp` can regenerate the match PDFs with updated times (they also note what the offset is) and its screens display what the current delay is

(Note: the actual people doing each role may change with shifts)

**Comment by sedders123** [comment]
Made good progress on this today. Updated #81 with volunteer roles required. Will hopefully be finalising first draft of a plan this weekend
