### ISSUE TITLE
Arrange for kit testing equipment

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#116]
We should have kit testing equipment available at the venue.

**Comment by RealOrangeOne** [comment]
Most of this kit is in the cupboard, and just needs to be shipped with #189

**Comment by jcwilliamson** [comment]
Can I get a brief list of exactly what we'd like the uni to provide us with?
Tyler mentioned bench PSUs, and I was thinking perhaps some of those red handheld DMMs from the lab could be useful, but can anyone think of anything else?

**Comment by RealOrangeOne** [comment]
Multimeters would definitely be a good shout.

**Comment by jcwilliamson** [comment]
Also, what sort of numbers do we need them in?

**Comment by RealOrangeOne** [comment]
Multimeters are generally quite useful, so something on the order of 2/3 will be fine. I suspect we'll be fine with a single bench PSU.

**Comment by kierdavis** [comment]
I'm not sure how wide the scope of testing kit during the competition is (it feels much more efficient to just swap the misbehaving piece of kit with another and debug it when we're less on fire), but an oscilloscope would be useful if we're digging into electronics problems.

**Comment by RealOrangeOne** [comment]
I tend to agree. We should ensure there's a good box of spares setup ready. I suspect common tools like multimeters, a bench PSU, maybe an oscilloscope will be generally useful for diagnosing other issues with kit, rather than issues with a board itself. I don't think we're going to need anything more complicated than that.

**Comment by PeterJCLaw** [comment]
I don't think we need a bench PSU at the competition. I agree with @kierdavis that we should err on the side of swapping out.

Multimeters are likely useful though. Maybe a couple?

That's probably it though.

**Comment by trickeydan** [comment]
If I'm diagnosing kit, I would want the following equipment ideally:
- Scope - this is invaluable for complex issues.
- Bench PSU
- Multimeter
- Motor Rig
- That beefy server PSU in the broom cupboard

I suggest getting at least 3 multimeters.

**Comment by trickeydan** [comment]
Update: I have obtained a loan of a Digital Oscilloscope for the duration of the event.

**Comment by jcwilliamson** [comment]
That's great news, that makes my job significantly easier.

**Comment by jcwilliamson** [comment]
Jeff in building 16 has agreed to loan us a bench powersupply and some handheld multimeters

**Comment by PeterJCLaw** [comment]
@jcwilliamson great news, thanks.

@trickeydan are there any failure modes which need a scope would diagnose that could be resolved without removing the case of the board in question? (I'm assuming not)

I'm of the view that anything which gets anywhere near needing a scope in order to be investigated should instead be solved by replacing the board, as was discussed above.

We shouldn't be considering doing deep investigations of kit failure at the competition. We will not have the time and it won't be expedient for teams.

Additionally, having more expensive kit around is a liability as it means we need to worry about it being damaged or going missing. We can likely cover the multimeters, but I don't think we want to be worrying about PSUs or scopes.

I would much rather see time invested in fixing some of the kit we have so it can act as spares. If we have time for that I can dig out the list of what numbers of parts we had before Kickstart for reference if that would be useful, though I'm reasonably sure the [inventory](https://github.com/srobo/inventory) is up to date.

**Comment by Tyler-Ward** [comment]
Arranged see #200 for collection tracking
