### ISSUE TITLE
Incoming ops team and outgoing ops teams should wait in different places

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1199]
We should have queueing locations to separate incoming and outgoing teams for the match ops cycle

**Comment by prophile** [comment]
I think we had a miscommunication in the wording of this issue—I think this is about teams of competitors not teams of ops staff.

The problem was that the teams waiting to come into a match were waiting by the exit desk, blocking teams recovering their robots from the previous match. We should separate them either spatially or temporally.

**Comment by samjmartin04** [comment]
This is included as part of organising match ops https://github.com/srobo/tasks/issues/1435 under planning how robots/competitors enter/exit the arena.
