### ISSUE TITLE
Have a way to close the power tools area

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1210]

**Comment by samjmartin04** [comment]
I don't think this is something we want to have. In SR2024, the power tools area was closed during the Knockouts, with the idea that teams would go to Helpdesk for it to be reopened if they needed to use it. It was discussed after that this is something we don't want to do because:
- The power tools area supervisor has a radio and is near the first aider (can be reduced by moving a shepherd to them)
- The Knockouts are particularly high pressure and high stress, so competitors having to go to Helpdesk and then to the power tools area would lead to them rushing more.

**Comment by sedders123** [comment]
We wont close the power tools area
