### ISSUE TITLE
Make sure there’s a no-show team process

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#1213]
While we do confirm with teams ahead of time whether they're going to turn up to our events, inevitably some don't turn up or are late arriving.

We should have a process for reacting to this, both in terms of how we'll communicate with the team and how we'll communicate and respond internally.

This could be that we'll call the supervisor a few times, though defining things like:
 - how we'll know they're absent (e.g: check with reception)
 - how long to wait after the start of the event
 - how much to try to get in contact with the supervisor (if e.g: the call goes to voicemail)
 - what triggers contacting the secondary contact
 - if/when we drop them out of the competition (if applicable to the event)

This procedure might be the same for all events or might be different by event.

Required actions:
 - [ ] ~Define process for Kickstart~
 - [ ] Define process for Tech Days
 - [ ] Define process for Competition

**Comment by sedders123** [comment]
@PeterJCLaw @raccube Is this something you could take a look at as part of the Team Support area?

**Comment by PeterJCLaw** [comment]
https://github.com/srobo/recurring-tasks/pull/108 adds this to the recurring tasks. Have updated this ticket to act as the instance for SR2025.

**Comment by PeterJCLaw** [comment]
This may relate to the reception process #1477.

**Comment by PeterJCLaw** [comment]
Relevant parts of the day schedules:
* Saturday: 10am - Opening Ceremony, 10:15 - Tinker Time, 11:20 - first league matches
* Sunday: 9:15 - Tinker Time, 10:20 - League Matches

TODO: who owns this process on the day? It could be the Team Support lead, but it being owned by Reception might be easier.

We expect teams to have all arrived in time for the opening ceremony, so if any teams aren't present at 9:55 on Saturday we should probably consider them no-show and reach out to them. This would mean:
- comparing actual arrivals to those expected, identifying those missing
- check in Discord and on teams@ to see if they've posted that they're on their way & running late; ignore those teams for now
- phoning the supervisors for any which are missing
  - if you get through, explain who you are (first name, volunteer for SR) and why you're calling (just checking they're on their way, how's their travel going, do they have an ETA)
  - if you don't get through, leave a voicemail and invite them to get back to us (ideally a phone call). TODO: can we have a phone number for the venue so we don't need to give our volunteers' own numbers?
- note down the outcome here, classify teams into one of: on their way, left voicemail, dropped out.

If the team confirm they aren't coming we will update the compstate to mark them as "dropped out before" the first match of the day; note this is very hard to undo once matches start, so only used it the team explicitly confirm they're not coming

If there are lots of dropouts and matches haven't started and we have a ready-to-go schedule for the reduced number of teams we should swap to that, to avoid lots of gaps in matches. Probably only worthwhile if the number of such teams is more than two, but somewhat depends on how the match schedule looks.

Repeat this at 11:00 on Saturday for any teams still not present.

At 11:15 (TODO: what would they be doing at that point?) provide an update to the Head Shepherds regarding which teams are present or not -- at this point teams may be in one of three states: present, AWOL, dropped out. The Head Shepherds can cascade this down to their teams ahead of the matches.

After 11am Saturday, Reception should actively inform the person running this process of new arrivals as they arrive. Reception should also inform the Head Shepherd.
TODO: Are the people doing the shepherding the same as the ones who were guiding teams to their pits? If so, who guides the team to their pits if they're late?

@Alexbruvv (as you've been working on reception stuff) and @samjmartin04 (as Match Ops), thoughts on this?

TODO: Sunday would be broadly similar, though with different timings and wouldn't touch the league schedule.

**Comment by samjmartin04** [comment]
> TODO: who owns this process on the day? It could be the Team Support lead, but it being owned by Reception might be easier.

Reception owning this would be easier, but we'll want/need this to be a member of the competition team.

> note down the outcome here, classify teams into one of: on their way, left voicemail, dropped out.

Think this section needs more clarification about how it's being noted, particularly if a team drops out. If a team drops out, the (current) Head Shepherd, Head of Match Ops, and Competition Software Coordinator all need to know. My intention is to have many ready-to-go schedules, so I'd almost certainly want to switch to a different schedule, so from my side, it'd just be a thumbs up from me for the Competition Software Coordinator to switch into a new schedule.

> At 11:15

Do we want to push this slightly earlier? If we just couldn't get through to a team at 10, but can at 11 that is a no-show/drop-out, then ideally we'd still want to update the match schedule, but it'd be too tight for timing at this point. As an aside, there's probably a length of time before the first match where we don't want to adjust a schedule as a team's first match will change, so perhaps this is fine if we decide not to update the match schedule after 10:40ish?

> provide an update to the Head Shepherds

May be useful for other people, e.g. Head Judge, Head of Match Ops, Helpdesk, to know that a team hasn't turned up, but these are much less time critical than the Head Shepherd knowing, so perhaps a message in Slack would be adequate for this.

> TODO: Are the people doing the shepherding the same as the ones who were guiding teams to their pits? If so, who guides the team to their pits if they're late?

Effectively yes. I think the more important part of this is the Health & Safety stuff from the Opening Ceremony that will be missed, so we'd need someone to tell them this (probably needs to be a more experienced volunteer too).

**Comment by PeterJCLaw** [comment]
Thanks for the review :)

> Do we want to push this slightly earlier? If we just couldn't get through to a team at 10, but can at 11 that is a no-show/drop-out, then ideally we'd still want to update the match schedule, but it'd be too tight for timing at this point.

For context: historically we've avoided updating the schedule too much on the day due to the potential for teams to turn up later, general confusion (historically we had printed schedules though haven't used them recently), risk of breakage, etc. I think we're a bit more comfortable with the system now, but I don't think we'd want to be changing the schedule in a hurry if we can avoid it.

In general I don't think we should change the schedule on the day unless we've had an explicitly confirmed drop-out that we didn't know about ahead of time, which I'd expect to be rare. Recovering from a team turning up late and having to add them back in to the schedule is non-trivial and not something I'd want to be trying to figure out on the fly.

Happy to pull this earlier, though I probably wouldn't come much earlier. My goal was for this to be as late as practical but no later. Agree 5 minutes is tight if we want to change the schedule at that point. What timing did you have in mind?

> Think this section needs more clarification about how it's being noted, particularly if a team drops out.

:+1:

> If a team drops out, the (current) Head Shepherd, Head of Match Ops, and Competition Software Coordinator all need to know.

Yup, definitely. I don't think they need to know interactively though -- my intent was that these people (though I forgot about the Competition Software Coordinator) be at the 11:15 meeting. My assumption here is that the presence (or lack thereof) of a team doesn't affect these people meaningfully (if at all?) until then.

> As an aside, there's probably a length of time before the first match where we don't want to adjust a schedule as a team's first match will change

Actually with how the system works, the constituents of the first match don't change when changing the schedule. The next few matches are also very unlikely to change unless teams are having a very early second match in one schedule and not in another. A dropout being in an early match of course would change things.

Details: the import mapping is such that the _layout_ of teams within the venue determines the initial matches; from there the mappings are worked backwards to the ids in the schedule and then forwards again to the rest of the schedule. This ensure that if robot inspection starts at the right place within the venue and follows the proper (linear, non-looping) path they're also incepting robots in the same order as their matches will happen.

**Comment by samjmartin04** [comment]
> which I'd expect to be rare

Yeah, it's probably not super common, but if we are actually calling the team, there's a decent chance that they will answer and be able to tell us that they aren't turning up. 

> What timing did you have in mind?

I'd say keep the current time for it (the 11:00 2nd check) and we decide a time where we won't update schedules by. Probably something like not changing the schedule after 10:30 or something.

> 11:15 meeting

Hadn't realised you'd intended it quite like that. Bear in mind that this would have to be in the cube for the Head Shepherd. A quick meeting could help transfer of information, or it's something that the Head of Match Ops gets the information about and then passes this information on. If we aren't changing schedules at this point, then there isn't necessarily a great rush to get them marked on SRComp and (whilst not necessarily required) is handy for the Head Shepherd to know (for their calls and to inform Shepherd in that area). 

Also realised that it'd also be handy for Robot Safety inspectors to know, so they know they don't have to rush to complete an inspection before match. I suspect it's probably easiest for one person (whether that's the person that made the phone calls or e.g. Head of Match Ops) going round and telling these people?

> constituents of the first match don't change when changing the schedule

Ah that's handy then. Perhaps could push my ~10:30 to be slightly later in that case then as that was one of my bigger concerns with changing the schedule more last minute

**Comment by PeterJCLaw** [comment]
> it'd also be handy for Robot Safety inspectors to know

Good shout. I suspect actually they'd want to know a bit earlier, since we expect that by 10am all the teams would have arrived. Maybe they should be told the state of play at 10 and then (also) updated later?

> it'd also be handy for Robot Safety inspectors to know, so they know they don't have to rush to complete an inspection before match.

Hrm, something this process doesn't account for is that if a team which happens to be late is in the first couple of matches then the inspectors might still need to rush. Should we account for that here/somewhere?

> I suspect it's probably easiest for one person (whether that's the person that made the phone calls or e.g. Head of Match Ops) going round and telling these people?

Just for clarity -- are you suggesting that the folks (including e.g: inspectors) who merely need to be informed of the outcomes are told individually by someone relaying a message to them? (Rather than being at the meeting)

I think I'm weakly in favour of a meeting if we can do that -- so that any questions/concerns can be raised/decision made in one go, but I don't know what it would interrupt.

Just so it's in one place, the list of people we think need to have at what I'll call the "coordination meeting":
- (person running this process)
- Competition Software Coordinator; inform, potential actions
- Head Shepherds × 3; inform
- Lead Robot Safety Inspector; inform
- Head of Helpdesk; inform
- Match Ops Area Owner; confirm schedule change (if any)
- Team Support Area Owner; confirm dropouts

You mentioned Head of Match Ops -- by that do you mean your area owner role, or the role which is head of a Match Ops shift? (I'm kinda bucketing the latter under "Head Shepherds" as I couldn't remember the name and think that all three of them [including the off-shift one, assuming we're doing that again] should be informed).

Question: do we want the Team Support Area Owner to be at the meeting, to sign-off on the drop-outs?
I feel like we shouldn't need that if we have an agreed process and trust those involved, plus that's potentially quite a lot of people pulled away from other things. (That said, I suspect that this year the Team Support Area Owner, Competition Software Coordinator and person running this process may be the same person this year :raising_hand:) 
The main reason I can think that they'd want to be there is if there were anything key to decide; I doubt we'll be able to think of everything the first time on a new process.

---

Regarding timings, how about:
- 9:55 -- first round of calls to AWOL teams
- 10:10 -- inform Safety Inspectors of current state
- 10:50 -- second round of calls to AWOL teams (also the point at which Reception switch to informing actively on new arrivals rather than just recording for later polling)
- 11:05 -- coordination meeting

I think that creates enough space after the coordination meeting to make changes if we need to, while keeping it late enough that we've had enough time for late teams and two rounds of contacting teams.

**Comment by samjmartin04** [comment]
> Should we account for that here/somewhere?

Sounds like it'd be useful to, but that may be accounted elsewhere.

> are you suggesting that the folks (including e.g: inspectors) who merely need to be informed of the outcomes are told individually by someone relaying a message to them? (Rather than being at the meeting)

I'm not sure a meeting is necessarily needed? To me, this feels like we need to inform particular people about which teams have dropped out/might be late, rather than a discussion about it? A meeting might be a pain to coordinate as it'll involve taking people (particularly robot safety inspectors who will be very busy at this point) off of their roles. I think I see it as ~15 seconds of information that needs to be imparted on someone. A meeting will take far long than that just waiting for everyone to turn up.

> Head Shepherds × 3; inform

We only need to inform the current Head Shepherd as this information will be passed on as Head Shepherds (and other Shepherds) go on shift.

> You mentioned Head of Match Ops -- by that do you mean your area owner role, or the role which is head of a Match Ops shift?

Area owner role, as it'll ultimately be their decision whether to change the schedule or not.

> Question: do we want the Team Support Area Owner to be at the meeting, to sign-off on the drop-outs?

Probably handy to have. Head of Helpdesk is probably useful too as I suspect they'd like to update their Helpdesk system if a team isn't there?

> potentially quite a lot of people pulled away from other things

Yeah. I think a meeting is overkill and takes too many people away from roles. Having someone going round and informing these people would be adequate I would have thought?

> 11:05 -- coordination meeting

I don't think we want to be making schedule changes this late. If people turn up a few minutes late, this quickly becomes 11:10 before the meeting happens, perhaps 11:15 before it ends, which is getting *very* close to matches starting. I think I'd like game area owner and competition software coordinator to be informed after the first meeting if a team has definitely dropped out and then don't touch the schedule after that (or don't touch after the previously mentioned ~10:40 cut-off).

> constituents of the first match don't change when changing the schedule

Just thought about this more. This is great, unless a team in the first couple of matches is one of the drop outs. I'm guessing teams would only move 1 match earlier, but we don't want to be making schedule changing quite close to the first match in this scenario.

**Comment by PeterJCLaw** [comment]
After each round of calls we want the person running this process updates the helpdesk system to note delays & dropouts. This relies on the person running the process being very explicit with the team that dropping out means they will not be able to compete.
Once they have done this, they inform the Match Ops Area Owner.

The Match Ops Area Owner will then:
- decide whether or not a schedule change is needed (this only applies after the first round of phone calls), and
- disseminate the information:
  - to the Competition Software Coordinator
  - to the (current shift) Head Shepherd

Others will find out via Helpdesk, which is coordinating the other affected activities.

**Comment by PeterJCLaw** [comment]
Regarding timings:
- 10:00 -- first round of calls to AWOL teams
- 11:00 -- second round of calls to AWOL teams (also the point at which Reception switch to informing actively on new arrivals rather than just recording for later polling -- done by phoning Staging)

**Comment by PeterJCLaw** [comment]
> TODO: can we have a phone number for the venue so we don't need to give our volunteers' own numbers?

Do we know enough about the venue phones to answer this now?
