### ISSUE TITLE
Plan SR2024 Kickstart Livestream

### ISSUE THREAD

**Issue by sedders123** [srobo/tasks#1228]
We should figure out the technical side of the livestream, assign a producer, and ideally plan and execute a dry run.

**Comment by RealOrangeOne** [comment]
@antonnikitin97 interested in owning?

**Comment by antonnikitin97** [comment]
Absolutely.

**Comment by antonnikitin97** [comment]
Are we planning to run this is as a virtual livestream or in-person? (Like what we planned for the virtual comp)?

**Comment by RealOrangeOne** [comment]
I think we discussed this at some point, and because there's less spectacle for kickstart, it's a much shorter event, and generally only 1 host anyway, it's probably not worth trying to do things in person. We did the virtual competition remotely and it worked fairly well, so we can probably just do the same.

**Comment by antonnikitin97** [comment]
Yeah I agree.

**Comment by antonnikitin97** [comment]
We held a dry run last Saturday, it went well. We know what we need to do, I'm closing this.
