### ISSUE TITLE
Plan layout for teams

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#123]
In concert with #65, this will go in https://github.com/srobo/comp-floorplans and would ideally use a similar build mechanism (see the 2017 folder) for integration with SRComp.

The crux of this task is therefore not to place teams individually, but to identify sufficient spaces where teams can be placed and create the layout diagrams with suitable place-holders.

**Comment by PeterJCLaw** [comment]
For reference, there are some old plans in https://www.studentrobotics.org/cgit/arena.git/tree/comp13/floorplans which _might_ be useful. I still suggest putting the new plans in the https://github.com/srobo/comp-floorplans repo though, since that seems to be the current standard.

**Comment by Tyler-Ward** [comment]
@PeterJCLaw what do we need to wort out where teams are as I think this is the longest blocking chain once the team layout is done as this blocks on competitor maps.

**Comment by Tyler-Ward** [comment]
@RealOrangeOne Have you contacted teams to see if any have students with mobility issues in them.

**Comment by RealOrangeOne** [comment]
I plan to contact teams as part of https://github.com/srobo/core-team-minutes/issues/89, which I intend to send out Monday. I'll be sure to add a requirement on the mobility issue as son as possible.

**Comment by PeterJCLaw** [comment]
Copied from https://github.com/srobo/tasks/issues/92#issuecomment-471088773:

My expectation here is that the original files will include placeholders such as TLA1, TLA2 etc. and then be templated with the actual team identities once we have a more concrete idea of which teams are actually coming and have sorted out the league schedule (#103).
This is what we've done in the past in order to ensure that teams can be inspected in order of first matches while ensuring the robot inspectors have a shortest-path to walk along.
I've found that a Hilbert curve is a useful pattern to use for the layout in order to achieve this effect.

I suggest having a look at how the [2017 floorplans](https://github.com/srobo/comp-floorplans/tree/master/2017) worked to get an idea of this.

**Comment by Adimote** [comment]
This is blocked on getting the disability info from teams

**Comment by Tyler-Ward** [comment]
@RealOrangeOne when is the deadline for teams letting you know if they have mobility requirements?

**Comment by trickeydan** [comment]
> The crux of this task is therefore not to place teams individually, but to identify sufficient spaces where teams can be placed and create the layout diagrams with suitable place-holders.

Isn't this done and on the floorplans?

**Comment by RealOrangeOne** [comment]
> when is the deadline for teams letting you know if they have mobility requirements

I didn't give one, out side of "ASAP". We're only at ~70% open rate, but I suspect we'll see something through soon. 

As the ticket description states, this ticket is for allocating team pit locations, rather than which teams go where. I suggest we close this ticket, and create a new one for allocating positions. Allocating positions isn't an urgent issue, and we can theoretically modify it on the setup days themselves.
