### ISSUE TITLE
Order trophies for SR2024

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#1348]
Decision made not to engrave sponsors on trophies, instead using the approach for SR2023 of printing their logos on the award card we present alongside the trophy

**Comment by Adimote** [comment]
Comparing our usual two suppliers:

## Trophystore.co.uk

- [20.5cm](https://www.trophystore.co.uk/peak-jade-glass-plaque-award-20-5cm) - £31.49
- [22cm](https://www.trophystore.co.uk/peak-jade-glass-plaque-award-22cm) - £33.49
- [24cm](https://www.trophystore.co.uk/peak-jade-glass-plaque-award-24cm) - £35.49

Plus a £12 set-up fee which we might be able to avoid because we used them last year

## Trophies2u.co.uk

Weirdly their site says "Available in 3 sizes" but they only have 2 on the page. Maybe we can email them to resolve this.

- [20cm](https://www.trophies2u.co.uk/shop/great-style-slant-jade-glass-award/) - £29.99
- [24.5cm](https://www.trophies2u.co.uk/shop/great-style-slant-jade-glass-award/) - £33.99

**Comment by Adimote** [comment]
I've emailed Trophies2u.co.uk to check if they still stock the 21cm size. 

So I can them easier, here's 
[the order from SR2023](https://github.com/srobo/tasks/issues/1116)
[the order SR2022](https://github.com/srobo/tasks/issues/857)

**Comment by Adimote** [comment]
I've sent the order email to the enquiries@ address from their [contact us page](https://www.trophies2u.co.uk/contact-us/). They normally happilly accept orders via email instead of their (admittedly pretty limited) web form.

Here's the text of the email:

> Hello!
> 
> We'd love to order 5x "Great Style Slant Jade Glass" trophies of varying sizes, all engraved with our logo + text. Exact text is in the table at the bottom of this email.
> 
> You should have our logo on file already, but in case it's convenient, I've attached it to this email in both SVG and PNG form.
> 
> Please note the font for the engraved text is '[Open Sans](https://fonts.google.com/share?selection.family=Open%20Sans:ital,wght@0,700;1,700)' Bold 700. Something similar is also acceptable.
> The logo image file includes the 'STUDENT ROBOTICS' text, so no need to match fonts for that.
> 
> Also please note the "2024 Final Frontier" text should be italic.
> 
> I've also attached a .pdf mockup of what we expect the design to be.
> 
> The address is different from last year, please ship & bill to:
> 
> \<Address Censored\>
> 
> Many thanks for providing this service!
> What follows is the table of engraving text and the trophy sizes:

Then I attached a copy of the first tab of the [trophy order calculation google sheet](https://docs.google.com/spreadsheets/d/1mhUBwacWYIGjyKDVEZ8jzGehU24Z-NIlHVMkgKpxxjk/edit#gid=0) (I left out the price column just in case they quote something slightly cheaper :)

I also attached the logo files:
- [Logo.svg](https://user-images.githubusercontent.com/2551763/224493808-39767f55-0d0e-48c1-9171-b3e3e1edbc88.svg)
- [Logo.png](https://user-images.githubusercontent.com/2551763/224493809-607bd204-76b1-4e03-a0d3-fbc5741e4326.png)

And a PDF mock-up I threw together in inkscape:
[Student Robotics Trophy mock.pdf](https://github.com/srobo/tasks/files/14624941/Student.Robotics.Trophy.mock.pdf)

**Comment by Adimote** [comment]
See price calculations here: 
https://docs.google.com/spreadsheets/d/1mhUBwacWYIGjyKDVEZ8jzGehU24Z-NIlHVMkgKpxxjk/edit#gid=0

I'm expecting this to cost £187.14, including VAT.

**Comment by RealOrangeOne** [comment]
Trophies have arrived.
