### ISSUE TITLE
Create safety test checklists

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#140]

**Comment by kierdavis** [comment]
?

**Comment by pringon** [comment]
Would making a PDF out of the checklist on page 11 of this year's rulebook be enough?

**Comment by PeterJCLaw** [comment]
There's a previous guide sheet at http://scarzybrook.co.uk/SR/robotinspector.pdf, though I don't know what the license is. I've emailed the author to see if we can license it (for inclusion in the runbook, though it seems also likely to be useful here).

**Comment by RealOrangeOne** [comment]
Assuming we can get the source for this too, that'll cover it. If not, we can just recreate it.

**Comment by PeterJCLaw** [comment]
For clarity: I'm _not_ expecting that the document I linked to will be directly usable -- it talks about high-vis jackets which I'm not sure if we're using this year? (see also #139)

**Comment by PeterJCLaw** [comment]
Update: we can indeed license http://scarzybrook.co.uk/SR/robotinspector.pdf under Creative Commons Attribution-ShareAlike 4.0 International.

**Comment by RealOrangeOne** [comment]
Do we have access to the *TeX source for this? It would be really good to base the document we end up using from this. Alternatively, we could just markdown-ify it and move it to the runbook?

**Comment by PeterJCLaw** [comment]
I'd not thought to ask, however I suspect that running the document through `pandoc` to regenerate the markdown is likely faster.

**Comment by PeterJCLaw** [comment]
```
$ pandoc robotinspector.pdf -o robotinspector.md
pandoc: Unknown reader: pdf
Pandoc can convert to PDF, but not from PDF.
```
Or not. Still, copy/paste & fixing to markdown is pretty quick for a document of this size.

**Comment by RealOrangeOne** [comment]
That's fine, we can do that on the hack day really quickly.

**Comment by Adimote** [comment]
Scarzy is doing this, please assign him once he accepted the invite.

**Comment by Scarzy** [comment]
I was thinking about this, and I'm not sure we need any additional documentation for this. Mainly because a checklist risks becoming too restrictive whereas this is something that requires a lot more common sense. I definitely don't want a robot getting all ticks and therefore passed whilst something not on the list actually makes it unsafe (it also becomes very hard to explain to the teams that despite the fact they've got all ticks they still don't get a high-vis).

The rules do specifically state:
> the inspector will use their own judgement and common sense when assessing your robot, and your robot may be judged to be unsafe for reasons or features not listed here.
As such a specific checklist seems at best superfluous.

On that basis, unless anyone thinks otherwise, I'll mark this ticket as closed.

On a not entirely unrelated note, I'll dig the source out some point (probably after the competition) so that it can be correctly markdown-ified.

**Comment by RealOrangeOne** [comment]
> This is something that requires a lot more common sense

I generally agree with this, having a specific checklist for what constitutes _safe_ will probably end badly. I think it's worth having a list of things which aren't necessary safety related, but still come under the pre-competition check, namely:

- 50x50x50cm bounds
- Battery is correctly protected
- All power (unless consent otherwise given) comes through the power board

I realise this comment now basically defines this list. I suspect wording the checklist as a minimum requirement rather than an absolute one will also achieve what we need.

**Comment by Scarzy** [comment]
@RealOrangeOne See the first 3 bullet points in the Robot Inspector guidance :P 

To clarify; I see no need for _additional_ documentation. I'm still expecting the Robot Inspector document and the rulebook to be used.

**Comment by RealOrangeOne** [comment]
That's exactly where I got said points from.

In that case yes I second that this issue can be closed, considering we have said document and it can be referenced.

**Comment by RealOrangeOne** [comment]
Related to this, there is also a list of testing points in Appendix B of the rules.

**Comment by Scarzy** [comment]
Yup, well aware. Hence the comment " A copy of the relevant sections of the
rulebook will be provided on the day. " in the document.
