### ISSUE TITLE
Arrange a first aid presence

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#142]

**Comment by RealOrangeOne** [comment]
I believe most teachers need to be first aid qualified (or at least trained), which helps. Many volunteers are first-aid qualified too, but it would be good to quantify all these

**Comment by kierdavis** [comment]
University security have first aid training too.

**Comment by prophile** [comment]
I believe we are covered by university security here: may we close this @trickeydan?

**Comment by trickeydan** [comment]
Kajetan is unsure as we need to have separate insurance. They are definitely first aid trained though.

We should enumerate a list of first-aid trained volunteers in my opinion.

**Comment by RealOrangeOne** [comment]
We should chat with SUSU about this.

**Comment by Adimote** [comment]
Blocked on SUSU Meeting

**Comment by Tyler-Ward** [comment]
This wasn't discussed with SUSU what do we actually need to know from SUSU for this.
The uni security are first aid trained, I think what we need here comes down to our risk assesments #66 @Scarzy opinions on this

**Comment by Scarzy** [comment]
We need a first aid presence, and whilst it could be provided by blueshirts with the relevant certification, for various reasons I'd rather it was provided by an external source. Issues of insurance/liability etc. fall into this, but the other thing to consider is what we need blueshirts to be doing during at the time. In the event of a minor incident it merely means a blueshirt may be pulled away from a role they are required in to perform 1st aid (and before anyone questions it; yes, 1st aid would take priority over ANY other role, even if it means the final match has to be halted). In the event of a more serious incident, we'd need the blueshirts to be managing the teams keeping them out of the way and informed. As such it in all instances it would be preferred to keep the blueshirts in a blueshirt role, not a 1st aid role.

If SUSU are providing the cover, that will be fine, and if they are providing it in the form of the nearby security guards, that would also be fine, so long as we have an easy way of contacting them in the event of an emergency. If memory serves, this is what has happened at previous competitions at Southampton Uni. We would also need that in writing from SUSU (including the form the cover takes (i.e. security), how to contact them, and the time period covered).

If we are using an external company, there are a few things to be considered;
   * We are probably looking at a cost of ~£500 for cover for the weekend.
   * They will need somewhere to spend the weekend, essentially their own pit, and ideally somewhere relatively quiet.
   * They would also need a secluded part of that area, so that they can administer any relevant aid out of the public view.
This is what we have aimed to do at Newbury the past few years.

**Comment by trickeydan** [comment]
@Scarzy 

> If SUSU are providing the cover, that will be fine, and if they are providing it in the form of the nearby security guards, that would also be fine, so long as we have an easy way of contacting them in the event of an emergency. If memory serves, this is what has happened at previous competitions at Southampton Uni. We would also need that in writing from SUSU (including the form the cover takes (i.e. security), how to contact them, and the time period covered).

Would a photo of their "Who to call if you need First Aid" sign be enough?

Alternatively: [Uni Security Contact Details](https://www.southampton.ac.uk/estates/what-we-do/security.page)

>     * We are probably looking at a cost of ~£500 for cover for the weekend.

Would you be able to get some quotes for that? It's definitely within budget.

>     * They would also need a secluded part of that area, so that they can administer any relevant aid out of the public view.

@WillB97 Could you find an area on the floorplan for this?

@Tyler-Ward When Will has found somewhere, please make sure that you add a First Aid station to the map.

**Comment by Scarzy** [comment]
Incidentally, I've just checked with a couple of teachers, and can confirm that there is no requirement whatsoever for teachers to have any first aid training.

**Comment by Scarzy** [comment]
> Would a photo of their "Who to call if you need First Aid" sign be enough?
> 
> Alternatively: [Uni Security Contact Details](https://www.southampton.ac.uk/estates/what-we-do/security.page)

No. Whilst that gives some confidence that they **can** provide it, I'd want something specific to our event to confirm that security **will** be the first point of contact on first aid matters.

> > * We are probably looking at a cost of ~£500 for cover for the weekend.
> Would you be able to get some quotes for that? It's definitely within budget.

I can chase some up at the weekend.

**Comment by WillB97** [comment]
L2 is already looking rather crowded, Bar 3 has space for this

**Comment by Scarzy** [comment]
First quote in, at £756

Some more still pending

**Comment by Tyler-Ward** [comment]
Who was that quote from for reference.

**Comment by Scarzy** [comment]
MET Medical, they are the same people who provided cover for SR2017

**Comment by Scarzy** [comment]
At this point I'm not expecting any more quotes to come in. Some requests are out there, but as they haven't responded I'm suspecting that they won't. It's worth noting that back in SR2017 one provider stated that they required a minimum of 6 weeks notice to cover an event. MET Medical consider anything less than 2 weeks notice to be a "late booking". I suspect we're just too late for them.

Is there the budget available should I need to book MET Medical on Monday?

**Comment by Tyler-Ward** [comment]
This quote is somewhat over the planned budget but given it is essential I can reallocate funds to cover this so this is approved. For reference what will MET medical be providing?

**Comment by Scarzy** [comment]
> For reference what will MET medical be providing?

Far more than we're likely to ever need, but it's what they provide as standard:

1x ECA / Medic / Ambulance Technician
1x Response Car: Oxygen, Defib, Entonox, Spinal Immobilsation, Emergency Lifesaving Drugs

**Comment by Tyler-Ward** [comment]
Just to check I assume this is for the Saturday and Sunday from 09:00 till 18:00 each day.

**Comment by PeterJCLaw** [comment]
If possible to get them to be around a little before and after the teams arrive and leave (respectively) I would encourage we do so. I'm more thinking of the evenings than the mornings, though I suspect we could have teams who arrive before 9am and hang around later than 6pm (the latter particularly on Saturday).

**Comment by Scarzy** [comment]
> Just to check I assume this is for the Saturday and Sunday from 09:00 till 18:00 each day.

They will turn up shortly before and leave shortly after those times (I'm pretty sure I read 15 minutes each way somewhere, but I can't find it atm)

> get them to be around a little before and after the teams arrive and leave

I could ask, but I suspect this will come with a price increase

**Comment by PeterJCLaw** [comment]
> > get them to be around a little before and after the teams arrive and leave
> 
> I could ask, but I suspect this will come with a price increase

The 15 minute buffer you mention is already included should be fine -- I'm mostly concerned that we've actively got cover during those times, rather than those being the times they're merely in the building.

It turns out that Saturday is listed as ending at 17:30, which allows for 30 minutes for teams being slow at leaving, which I think is plenty. (I'd thought we went until 18:00 on both days)

**Comment by Tyler-Ward** [comment]
For the first Aider location bar 3 will be quite open, Do these have to be one location or can they be two places? we could potentially use the dead end corridor just above bar 2 or down on L1 if we need an area out of the way but these wont be easy for competitors to find.

**Comment by Scarzy** [comment]
I managed to (quite accidentally) get them to reduce it to £648

This needs paying in advance, so I guess I need to send the invoice to
someone. Tyler, are you the best person for this?

**Comment by Tyler-Ward** [comment]
That is correct, email the invoice over to me and i will forward to the trustees for direct payment.

**Comment by Scarzy** [comment]
This has been booked. The invoice has been sent to @Tyler-Ward.

**Comment by Scarzy** [comment]
> For the first Aider location bar 3 will be quite open, Do these have to be one location or can they be two places?

Ideally they would be close together, however it's not strictly necessary. The area where the first aider will be stationed normally could do with being somewhere convenient/easy to find, but as pleasant as possible (the first aider will be sat there for quite some time over the course of the weekend!).

To be honest, the secluded area only needs to be an idea of where could be used if necessary, I highly doubt it will be used. So we could even use the volunteer area and just have a way of marking it temporarily out of bounds. The only other thing to note is that if the secluded area is not near the first aid station, we'd need a volunteer to be present there whilst the first aider isn't, so the teams still go to the same place and the blueshirt can go to get the first aider.

**Comment by PeterJCLaw** [comment]
Hrm, we were wondering about putting the battery charging in the volunteer area (not sure we thought it was a good idea, just one possibility). That would likely be incompatible with it being used as the secluded area as we wouldn't be able to leave the chargers which were in the middle of charging (though probably could shut them off?)

**Comment by RealOrangeOne** [comment]
Charging is no longer going in the volunteer area. Bar 3 would work better as a first aid post, as competitors will have better access to it. There's plenty of room there, and things going on. It's also fairly central to team pits.

**Comment by Tyler-Ward** [comment]
The first aid has now been paid for and the first aid point has been put on bar 3 in one of the booths.

**Comment by Tyler-Ward** [comment]
I think we can close this now unless there are any more points to cover @Scarzy

**Comment by Scarzy** [comment]
Yeah, I think this can be closed

**Comment by Scarzy** [comment]
For reference, I've just received a quote from AB-Medical for £1152
