### ISSUE TITLE
Book Hotels for volunteers

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#151]
It would be nice if they didn't have to sleep in the basement.

**Comment by Tyler-Ward** [comment]
relies on #168

**Comment by Tyler-Ward** [comment]
#53 will help this

**Comment by Adimote** [comment]
I did some rough calculations here https://docs.google.com/spreadsheets/d/1gFOVRFBejGHhtfM0uikfE2hYoQhh1pAgKRZJWfmdbbU/edit?usp=sharing (Shared only with @studentrobotics org because it has personally identifiable information, please request if you also want access)

Early numbers for hotel costs is best case £1,055 which is £55 over budget, that's assuming everyone shares double rooms with the optimal person.

**Comment by Tyler-Ward** [comment]
Thanks for looks at this @Adimote that level of overspend should be fine. I the plan to order the rooms now or to check with volunteers first

**Comment by Adimote** [comment]
I'm getting towards a final accommodation arrangement, as quite a few people have replied with updated availability. In the mean-time the hotel has gone slightly up in price, the new cost is £1,221.50.

I think things are stable enough to book now, so I'll phone them up Tomorrow morning (2019-03-13)

**Comment by Tyler-Ward** [comment]
We an work with that cost. Incase of any more fluctuations between now and when you book you are good to spend up to 1,300 on this.

**Comment by Adimote** [comment]
Booked! Total cost was 1259.50GBP

**Comment by Tyler-Ward** [comment]
Can you send me an invoice so i can add to the budget tracking
