### ISSUE TITLE
Add live stream to website

### ISSUE THREAD

**Issue by trickeydan** [srobo/tasks#162]
Depends on #77

**Comment by PeterJCLaw** [comment]
Note: the version of the website we use during the competition is a little separate from the main one, and lives in https://github.com/srobo/competition-website. There's a slot for a youtube link which would be a drop-in change (https://github.com/srobo/competition-website/blob/master/_config.yml#L19), though integrating other hosting should be pretty easy too.

If it ends up being facebook hosted, then the variant of that repo (my [`hugo-sb2018` branch](https://github.com/PeterJCLaw/competition-website/tree/hugo-sb2018)) I created for SourceBots last year might be useful -- I think that included a facebook stream. Note that that variant is based on hugo rather than Jekyll, so it's probably more useful as a reference than a transplant.

**Comment by PeterJCLaw** [comment]
Blocked on knowing who's doing the feed.

**Comment by Tyler-Ward** [comment]
Unblocked-we will use youtube

**Comment by PeterJCLaw** [comment]
Ack, let me know once we know what the link is. This is however a ~5 minute task and it can happen during the event if necessary, so no rush here.

**Comment by RealOrangeOne** [comment]
This requires the link to the stream to be done, which won't be setup until the competition. Therefore we can move it to a setup day task (it's more likely to be Saturday morning than actually _on_ a setup day).

**Comment by PeterJCLaw** [comment]
Blocked on knowing the url.

**Comment by PeterJCLaw** [comment]
@antoinepetty as you're setting up the youtube portion of this, would you like to also take this task?

**Comment by PeterJCLaw** [comment]
This is in review at https://github.com/srobo/competition-website/pull/4.
