### ISSUE TITLE
Some repositories from cgit require credentials when clonning them

### ISSUE THREAD

**Issue by pringon** [srobo/tasks#195]
Can confirm this is the fact for: https://www.studentrobotics.org/gerrit/p/rules-sr2013.git
Can most likely be fixed by fixing  #46 .

**Comment by PeterJCLaw** [comment]
Hi,

Thanks for reporting, however this is working as expected.

The repose which require credentials to access are those which were deliberately kept private for various reasons. In the case of the rules repo, it's private so that we can develop the rules without the competitors being able to see them (thus maintaining the surprise of the game until Kickstart).

The other repos I'm aware of being private are similarly intentionally so and with good reason. This is _not_ something which I would expect to change if we moved hosting (the rules repo _is_ on github, but is still private).

I'm therefore going to close this as invalid.

Thanks,
Peter

**Comment by Tyler-Ward** [comment]
This was for non private repos e.g. previous versions of the rules

**Comment by PeterJCLaw** [comment]
The rules are a somewhat special case here - they're pretty much the only repo we have for which it would be viable to do a post-hoc publication of their content. Would it be sufficient to maintain a (public) archive of the built rulebooks instead?

I think the piece I'm missing is why you want the old contents of the rules repo?

**Comment by kierdavis** [comment]
A use case I can think of is that we may want to reuse material (e.g. diagrams) when developing future rulebooks.

Why should the contents of these repositories remain secret?

**Comment by PeterJCLaw** [comment]
The linked rulebook was an aberration from the usual pattern, which is to simply continue development in the same repo each year. The current rules extend the content of that repo (i.e: the current `master` in that repo is present in the history of https://github.com/srobo/rules), so we're not losing nor hiding anything as those content _are_ available when developing future rulebooks.

**Comment by kierdavis** [comment]
Ah, I see. Nevertheless, is there a reason why `rules-sr2013` should remain secret, while in general all our other past rulebook sources are public?

**Comment by PeterJCLaw** [comment]
At this point not really, though it would be simpler to just delete that repo -- it's now causing considerably more issues merely by existing than it would if it was gone. (I don't know how to delete repos in Gerrit unfortunately and it's probably not worth it)

**Comment by PeterJCLaw** [comment]
Thanks again for reporting. I'm going to close this now as I believe it's clear why that particular repo is (unusually) private (but not worth fixing) and that other private repos are correctly so. In any case, as we're moving to GitHub (#179) I'm not sure it's worth investing deeply into sorting the permissions on `cgit`.

If there are other repos which you believe are incorrectly private, please do say.
