### ISSUE TITLE
Rehearse post finals sequence

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#197]
We should rehearse the post finals sequence on the setup days, Have assigned all those who will likely need to be involved.

**Comment by RealOrangeOne** [comment]
Rough schedule overview, based on previous years:

- Prizes are moved into position
- Match finishes
- Commentators close off the competition, and introduce guest speaker
- Turn the lights up a bit

- Guest speaker (#133 ) takes the stage and starts talking.

- Linesman score the match, with assistance from head judge if required
- Head judge confirms teams who win each award
- List of teams who won awards are given to _showman_ (me), ideally in fancy envelopes

- Present prizes (#128 )

**Comment by PeterJCLaw** [comment]
> Rough schedule overview, based on previous years:

Thanks for getting this started 👍 

>     * Prizes are moved into position
> 
>     * Match finishes

Where are the prizes being put in this sequence? At Newbury we've held the prize-giving _in_ the arena, This works well as pretty much everyone is already standing around it and has a comfortable view.

Is the plan to use the stage? If so, we need to bear in mind what else is on the stage at this point (namely people viewing the final).

> * Commentators close off the competition, and introduce guest speaker
> * Turn the lights up a bit
> * Guest speaker (#133 ) takes the stage and starts talking.
> * Linesman score the match, with assistance from head judge if required

We need to allow for the possibility of a tie-breaker. Scoring _must_ be conclusive before we move on.

(Please can we use "marshals" rather than linesman; note also that their role doesn't produce _scores_)

> * Head judge confirms teams who win each award
> * List of teams who won awards are given to _showman_ (me), ideally in fancy envelopes

We should do as much of this as we can _before_ the knockouts. Most prizes should be known by then and it avoids a rush.

Post-finals we can prepare the envelops _during_ the prize-giving if we want to (though I suggest that we don't)

**Comment by RealOrangeOne** [comment]
This plan was originally modified from the one in https://github.com/srobo/tasks/issues/128, which now has some changes requested, which I hope to get done in the next few days.

**Comment by RealOrangeOne** [comment]
Planning for this has now moved to #128

**Comment by Tyler-Ward** [comment]
it has been rehearsed
