### ISSUE TITLE
Inventory audit of storage

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#209]
Lowish priority but we should audit the inventory in storage as many things don't match between reality and the inventory.

**Comment by PeterJCLaw** [comment]
This mostly happened during #284.

The majority of _boxes_ in the container were identified and moved, though we did not attempt to validate their contents, instead relying on that being correct from the post-competition checking.

We were also able to identify a number of items which had older part code labels without barcodes. While we printed labels for these, unfortunately we were not able to add the labels to the boxes. The labels have been left in the container so that we can complete that task at another time (without needing to take a label printer to the container).

**Comment by PeterJCLaw** [comment]
I was at the container today; the apparently unlabelled RUBs I mentioned do in fact have labels, just on the back of them (they have since been turned around).

**Comment by PeterJCLaw** [comment]
While this hasn't strictly happened, I've recently been at the container a number of times and captured lists of all the RUBs which were there. Combining that with the RUBs which I've personally moved into and out of the container recently, I believe I can account for the correct presence of all the RUBs.

Looking at the list of non-RUB things which the inventory says are in the container, I'm also pretty sure that that's right too.

I'm therefore calling this done.
