### ISSUE TITLE
Place teams in pit locations

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#211]
The logical extension of https://github.com/srobo/tasks/issues/123.

Now that we have locations for team pits (https://github.com/srobo/comp-floorplans), we need to know where to place them. 

This should ideally be done on the setup days, to ensure even last minute announcements of needs can be accommodated. 

As this information is fairly sensitive, I will store the need on the master teams list for the competition, which is only accessible to the core team: https://docs.google.com/spreadsheets/d/1pZnPNSW9T7k5L2UgOzqcTBMCZlQclxDkjeHXuXqUqmk/edit

**Comment by PeterJCLaw** [comment]
If we want to mark the locations of each team on the venue maps #92 (which I think we do) and we want to print those (which I think we do), then we need to have decided which teams are where in time to print the maps.

I'd assume however that we can do that printing at the Uni (rather than needing to be done elsewhere), even though it would be in colour. We should check this assumption as if it turns out not to be the case for some reason then we will need to do this somewhat sooner.

**Comment by TomWheal** [comment]
If we want to use the uni print centre, (they can be expensive), their lead time is about a week.

**Comment by PeterJCLaw** [comment]
Ah, sorry, I meant printing a bunch of copies in labs (I'm assuming we can get some print credits for that).
Useful to have a reference lead-time though.

**Comment by Tyler-Ward** [comment]
This information will be needed by the 21st in order to get the required maps created and printed without relying on things not arriving if there is a delay. The map is included in #87. If we expect a last minute location request we have spare pits so can leave one spare on L2 which can be used if we get a problem. The entire venue is accessible though so they can be in other areas if we need to.

**Comment by RealOrangeOne** [comment]
Another point to consider with this is that teams vary in size, some as high as 35! We should ensure those teams with incredibly large teams are placed in locations with plenty of space around them, such as on L4.

**Comment by Tyler-Ward** [comment]
We currently have 32 teams and 34 slots in the maps, this allows for us to drop the two pit locations that @Scarzy had an issue with. The link below is a list of the currently active teams with just public information

https://docs.google.com/spreadsheets/u/1/d/1KVIMpXJ_9jPMLbg-hSe9WCY-D5Unru49LJVH6q-JD20/edit#gid=0

**Comment by RealOrangeOne** [comment]
There's 1 team who require placing on L2, besides that we can consider it a free-for-all

**Comment by Tyler-Ward** [comment]
Teams with location requirements have been identified.
We are planning on removing pits 1,7, and 22 and renumber the remainder to bring us to the correct number and moving 12 to make more room.

**Comment by sedders123** [comment]
Teams have now been allocated a pit

**Comment by PeterJCLaw** [comment]
@sedders123 would you be able to create a PR against the [compstate](https://github.com/srobo/sr2019-comp/) to add this information to it? (The [`layout.yaml`](https://github.com/srobo/sr2019-comp/blob/master/layout.yaml) and [`shepherding.yaml`](https://github.com/srobo/sr2019-comp/blob/master/shepherding.yaml) files are the ones of interest)

**Comment by sedders123** [comment]
See https://github.com/srobo/sr2019-comp/pull/2 :)
