### ISSUE TITLE
Plan setup schedule and organisation

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#220]
We need a plan for the setup days

**Comment by Tyler-Ward** [comment]
have created a setup schedule here for people to comment on

https://hackmd.io/OJmmlxSQTcKDVTHxnyLbGA

**Comment by Tyler-Ward** [comment]
I have also updated the document for takedown tasks. I haven't added any times yet other than on a half day basis as they are very dependant on how many volunteers are available, will try and fill in later if i have more time.

**Comment by PeterJCLaw** [comment]
I think that's reasonable.

What I'd meant was estimates on the number of people a task _should_ have, and then how long we expect it to take. This should be independent from the number of volunteers we have and would mean we can work out if we're going to have enough time.

I think that many of the tasks will already have such estimates from the past, so I'm hopeful that adding more shouldn't be too difficult. If there are things we feel we can't estimate, I think that's fine too though would be great if we could list them somewhere so that we can record how long they take this year.

For clarity: adding these estimates (to the runbook) is something anyone (ideally people who've been involved in SR setup before) can help with.

**Comment by Tyler-Ward** [comment]
volunteer requirements added to #81

**Comment by RealOrangeOne** [comment]
I think the plan looks fine overall.

I think we should split out the takedown tasks into Sunday evening, Monday Morning and Monday Afternoon.

We should also specify that we need training tasks done on the Friday afternoon for tasks such as reception, shepherding etc.

**Comment by Tyler-Ward** [comment]
The above has been added along with some other usefull notes.

Unless there are any more comments I think this can be closed

**Comment by RealOrangeOne** [comment]
I'm happy with this schedule :+1:
