### ISSUE TITLE
Make 'Sad Lipo' Bucket

### ISSUE THREAD

**Issue by sedders123** [srobo/tasks#240]

**Comment by Adimote** [comment]
Can this be a RUB filled with water?

**Comment by Scarzy** [comment]
Water, electricity, and lithium all sound like a fantastic combination...

**Comment by Adimote** [comment]
I thought the standard way to discharge in an emergency is in salt water?

**Comment by Scarzy** [comment]
What I read says that all that does in reality is corrode the terminals and
leave a fully charged battery with no way to discharge it. Salt water is
/sometimes/ used to remove the last little bit of charge on an otherwise
already discharged battery, but it doesn't seem to be recommended, and
especially not for a damaged battery.

The more recommended approach seems to be to put them in a fire proof
container and take them to a somewhere with a disposal scheme.

**Comment by sedders123** [comment]
A protocol was agreed upon at the competition

**Comment by Scarzy** [comment]
Can I suggest this protocol is documented? For future reference

**Comment by PeterJCLaw** [comment]
@sedders123 do you know what the protocol was? (cc @rgilton as head helpdesker)

**Comment by rgilton** [comment]
> @sedders123 do you know what the protocol was? (cc @rgilton as head helpdesker)

I was only "head helpdesker" during Saturday morning, and was not aware of any scheme for disposing of broken lipos.

**Comment by sedders123** [comment]
While we were eating lunch on the teardown day, I was told that there was a procedure and we could close this issue. Can't remember who said this, might have been @Tyler-Ward?

**Comment by RealOrangeOne** [comment]
I remember something about battery disposal points _around_ which could have been used if necessary.

**Comment by trickeydan** [comment]
If there was a protocol, I was unaware of it. I recall discussion where @Scarzy said that we should not use salt water as we had planned to. (Something something, lithium, fire, water, bad)

**Comment by Scarzy** [comment]
Ok, so it sounds like there wasn't a protocol.

I suggest this is re-closed, but is at least now no longer inaccurate.
