### ISSUE TITLE
Get a bench power supply

### ISSUE THREAD

**Issue by kierdavis** [srobo/tasks#300]
This would be very useful for kit testing.

Rough requirements I can think of:
- capable of 12V at a few amps.
- current limit

**Comment by TomWheal** [comment]
Im happy to own this

**Comment by trickeydan** [comment]
Do we have the budget for this currently?

We've been able to reliably borrow bench PSUs in the past.

**Comment by kierdavis** [comment]
this is not something I expect needs to be dealt with until the run up to
next year's kit collation. Let's see what happens in the budget department
in the meantime

**Comment by PeterJCLaw** [comment]
> We've been able to reliably borrow bench PSUs in the past.

This is unfortunately not the case. During the preparations and tidyup related to SR2019, ensuring that a bench PSU would be available was repeatedly a blocker to having kit sorting events.
It may have appeared otherwise as a result of all the events having a PSU, however that is a result of selection bias rather than truly representative (the events happened because we knew we'd be able to get a PSU, rather than the other way around).

**Comment by WillB97** [comment]
We now own a pair of Tenma benchtop power supplies.
