### ISSUE TITLE
Organise markers for the arena and tokens

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#448]
The arena (and, possibly, things inside it) is marked with libkoki markers, which need printing off in advance.
For the arena itself SR has some pre-printed libkoki markers on a plastic backing which are re-used each year. These need checking and ensuring they make it to the venue. Replacements may be needed for any markers which are showing wear.

### Original

[comp/game/markers](https://github.com/srobo/recurring-tasks/blob/master/comp/game/markers.yaml)

**Comment by RealOrangeOne** [comment]
The arena markers already exist, and we have enough spares not to worry about them. Markers for tokens still need ordering.

For SR2019, we used 210gsm card. This worked reasonably well, however was a pain to print and assemble.

Historically, markers were printed on 270gsm plastic by www.stormpress.co.uk. The plastic is *a lot* stronger, and comes pre-cut. For SR2019, these would have been 10x the price of card.

Because we have such a lead time advantage, I think it's still worth inquiring about plastic. With such a large amount of notice, we may be able to get a reasonable price!

**Comment by RealOrangeOne** [comment]
I've requested a quote from stormpress, to see what price would be like.

There are significant benefits to having someone else cut the tokens for us
