### ISSUE TITLE
Migrate IDE repos to srobo org

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#46]
Currently the IDE repos are spread between the srobo org, cgit, ~and @PeterJCLaw's account~. These should be moved over to the org, once correctly licensed.

The relevant repos are:
* https://www.studentrobotics.org/cgit/cyanide.git
* https://www.studentrobotics.org/cgit/pyenv-dummy.git
* https://www.studentrobotics.org/cgit/brain/zip-packager.git (maybe; it's arguably not part of the IDE and should perhaps be separately configured by our deployment setup with a dummy in the IDE repo)

**Comment by PeterJCLaw** [comment]
For clarity: the clones on my GitHub are merely my own clones of them. The repos on https://www.studentrobotics.org/cgit/ are canonical for all the IDE repos.

**Comment by PeterJCLaw** [comment]
Previously we had automatic deployment of updates to the repo (onto `saffron` at least), which is part of the reason that they have limitations about who can push to them directly. I think that a form of auto-deployment is a good thing (whether it be being pulled from `patience`) or some other mechanism, which means we're going to need to have some similar access protection (to gaurd against privilege escalation at the very least).

Viewing this as somewhat of the first set of repos we're going to migrate to a newer way of working on GitHub, I'm expecting that we'll end up with a similar setup for our other repos that we want to be able to auto-deploy.

One solution is:
- A new group (and eventually a small number of such groups) for the maintainer(s) of each _area_ of software, which are the only ones who can make changes to `master` branches in the relevant repos
- Tags on each of the repos, so that it's visible which repos are in which maintenance groups
- A _small_ number of people in each group, _all_ of whom are people we'd be happy to give root access to on our servers

The alternative approach I can think of delays deployment to involving patches to https://github.com/PeterJCLaw/sr-server-puppet/:
- relaxed development of the various repos on GitHub
- deployments happen via patches to https://github.com/PeterJCLaw/sr-server-puppet/ (or https://www.studentrobotics.org/cgit/server/puppet, I forget which `patience` has cloned from), with review at that stage from a limited set of root-trusted people

@RealOrangeOne thoughts?

**Comment by PeterJCLaw** [comment]
The IDE repos are now on GitHub. We've also now got the [srobo-legacy](https://github.com/srobo-legacy) organisation as well as some internal teams grouping.
