### ISSUE TITLE
Arrange a live stream for the competition

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#480]
We should have a live stream of the competition.
We'll need to work out:
 - what hardware & sofware will be used to drive the stream (both cameras and
 mixing desk/driver computer)
 - where the cameras for the stream should go

### Original

[comp/livestream](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream.yaml)

### Dependencies

 * ~#419 Have a competition network~
 * #584 Acquire hardware for the livestream
 * #585 Setup OBS config and rough livestream schedule
 * #603 Interview teams for inclusion in the live stream

**Comment by RealOrangeOne** [comment]
- Do Reading have a society which do things like this?
- Would SUSU TV do this?
- Could we borrow the same kit we used for SR2019?
- Could we run something ourselves? (As we did for kickstart)

**Comment by Tyler-Ward** [comment]
The kit I borrowed last year to do the livestream setup is as follows.

- 1* Powerfull compter with multiple monitor outputs and usb 3.0 busses (not just multiple ports) (Futureworlds) Intel hades canyon nuc
- 2* Elgato USB HDMI capture devices (Futureworlds)
- 2* Elgato streamdeck (Futureworlds)
- 1* usb soundard (SUWS) (this wont be hard to find)
- 1* mixing desk (SUSU)
- 1* wired microphone and stand (SUSU)
- 2* monitors (ECS)
- Assorted cables (multiple providers)
- 1* webcam (SR Kit spares)
- 2* gopros (volunteers)

The kit from susu can likley be borrowed from reading
The kit from SUWS can be easily found
The kit from FW might be hard to find elsewhere and as i am no longer based there I dont think i can borrow it again.
The montiors can probably be borowed from elsewhere do we have a ticket for this.
we already have the webcam
I assume that the volunteers who lent them last time still have their gopros.
The powerfill computer can probably be borrowed from a voluntter (This will need to be a decent spec both in cpu and graphics)

Ths software was OBS studio which is open source and the configs are still arround if we need them.

As for the other questions.

- Reading might but we would need to act soon if we want them to do anything as this will likley be during their holidays.
- We might be able to talk to SUSU tv but the distant location will make it more complicated for them. The issue last year was that no one was arround due to the holidays.
- See above for a more detailed answer.
- We ran it ourself last time we just borrowed the kit for it. The kickstart livestream bits i saw wernt great, we will need more than a laptop with its internal webcam if the livestream is to be atall usefull.

**Comment by PeterJCLaw** [comment]
Thanks for the info @Tyler-Ward, much appreciated.

**Comment by PeterJCLaw** [comment]
Current plan is for the managing desk to be in a far corner of the room with the arena in. This should keep it close enough to the action, while being far enough away from the noise.

The presenters will likely face into the room, with their backs against the window. This gives us the option of having the outside (grass field) as the background, or pulling the blind closed behind the presenters.

**Comment by PeterJCLaw** [comment]
Not sure if this is now a duplicate of the other livestream related tasks.

**Comment by antoinepetty** [comment]
The livestreams have been scheduled on YouTube - would you say that makes this done?

**Comment by RealOrangeOne** [comment]
I think the fact that we have scheduled livestreams already up, we know how the cameras will work, and we know how the supporting infrastructure will look, I think we're good.
