### ISSUE TITLE
Acquire carpet for the SR2020 arenas

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#501]
We currently use carpet as the flooring of the arenas. Usually the venue doesn't have an equivalent flooring underneath the arena area so we need to get some ourselves.
We need enough for all the arenas plus some spare for a testing area.

### Original

[comp/arena/carpet](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/carpet.yaml)

**Comment by RealOrangeOne** [comment]
I believe the carpet used last year is in Southampton.

@trickeydan I remember you commenting about the carpet at some point, can you confirm where it is?

**Comment by trickeydan** [comment]
> @trickeydan I remember you commenting about the carpet at some point, can you confirm where it is?

It is currently in B32 L3 North "Airport Lounge".

However, I am concerned about the health and safety of moving it from there to anywhere else. As you are aware, the carpet is heavy, and it is located rather high up. If my understanding of how it was placed there is correct, it was done in a very dangerous way.

Essentially, you will need to at the very least come up with a plan / risk assessment for moving it from there. There is furniture that will need moving out of the way also when moving it. The carpet will not fit in the lift of B32, so you will have to plan how to get it down the staircase safely. Due to working researchers in the vicinity of this location, it will also have to be moved after 18:30pm, or at a weekend.
