### ISSUE TITLE
Review the rules based on the virtual competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#591]
Now that the competition is virtual, we need to review the rules to make sure they're compatible and up to date with how the event will actually work.

We may want to add some new rules around conduct?

**Comment by PeterJCLaw** [comment]
Having a quick read through the rules, most of the things we're not doing are fairly obviously not applicable to a simulated competition. If that were entirely the case I'd be tempted to not bother issuing a new rulebook (for expedience).

However there is one thing which is a bit contradictory: we're _not_ using different marker sets for competition than development. I think it's highly unlikely that competitors would be surprised by this, though might be worth either fixing or calling out as a change.

It may also be useful to remove awards we're not offering (see #556).

**Comment by PeterJCLaw** [comment]
> However there is one thing which is a bit contradictory: we're _not_ using different marker sets for competition than development. I think it's highly unlikely that competitors would be surprised by this, though might be worth either fixing or calling out as a change.

I've just had a look at how this works in the real API and it turns out we don't need to do anything. The codes exposed in the real API are always in the range 0-100. Essentially it contains a lookup table from the real libkoki marker number to an instance of the apparent `MarkerInfo` for that id. This ends up (intentionally) masking the difference in code.
https://github.com/srobo/sr-robot-legacy/blob/4e6eebf23cb7e3f70f123f92d15b6c5cc772b17d/sr/robot/vision.py#L72-L91

**Comment by PeterJCLaw** [comment]
I'm calling this done, though I'll open a separate task for removing references to physical stuff in the rules.
