### ISSUE TITLE
Prepare a layout of the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#725]
This will need to specify where the arenas, team pits, reception, helpdesk and so forth are.
The outcome from this task should be an entry in https://github.com/srobo/comp-floorplans. 

### Original

[comp/venue/layout](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/layout.yaml)

### Dependencies

 * #724 Get fire plans from the venue

**Comment by Tyler-Ward** [comment]
@WillB97 as the plans don't have a cable drop from the balcony for the arena what is the planned cable route between the tech desk and the arena? For #790 we may need to borrow some SDI conversion gear from SUSU if the length is longer than a HDMI cable. we may also need some ethernet couplers as the current ethernet cables are at the length required for a direct balcony drop.

**Comment by WillB97** [comment]
Apologies, I uploaded the map that didn't detail the power and networking. That has now been corrected.

The network and power cables for the arena will run to the left end of stage. There will be a switch here that will connect back to the balcony over one of the ethernet ties.

I would expect that kit return would be done at reception. There is plenty of space around it to stack kits.

**Comment by PeterJCLaw** [comment]
> I would expect that kit return would be done at reception. There is plenty of space around it to stack kits.

Given past experience, I would expect kit returned to need considerably more desk space than is currently allocated to reception (and likely a different configuration of desks). All ~30 teams will be leaving at approximately the same time, so high throughput will be desirable to avoid delays. In the past we've allocated ~4 desks (with generous spacing) in addition to (a by-then reduced) reception, which I'd suggest is a reasonable starting point. We might also want to consider packing up the testing arena during the semi-finals in order to create more space for this purpose.

**Comment by WillB97** [comment]
Where are you trying to put the cameras? Remembering that there is no scaff running between the corners to attach to.

**Comment by Tyler-Ward** [comment]
Most likely on one of the corner monitor stands, or if that doesn't work on its own tripod

**Comment by WillB97** [comment]
I believe SUSU has long coax cables but we may still want to consider other connection methods.

**Comment by Scarzy** [comment]
There needs to be the ability to provide a private area for the first aider to provide treatment. In 2019 we used the volunteer rest area and volunteers were told if it was required they would have to leave, I suggest we do the same again unless another space is available.

**Comment by WillB97** [comment]
That seems appropriate. SUSU is generally open plan so private spaces are few and far between.
