### ISSUE TITLE
Organise drivers for the arena screens

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#735]
We have screens around the arena to display live information, these
need something to drive them.

In the past this has been Raspberry Pis displaying a web-page. If
this is used again then the following things need doing:
* Ensure we have enough Pis that work
* Ensure we have enough Pi power supplies that work
* Pre-load the Pis SD cards with the proper OS
* Label each Pi with where it will be deployed (e.g: Arena B, Corner 1)
* Ensure the Pis will have a suitable name/address on the network

### Original

[comp/arena/screens-drivers](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/screens-drivers.yaml)

### Dependencies

 * #734 Pre competition storage trip
 * #900 Arrange screen content

**Comment by PeterJCLaw** [comment]
If we can get the Pis to me I'm happy to do the checking & setup for this. The Pis are in the container, so whenever we next visit it might be useful to extract them.

**Comment by RealOrangeOne** [comment]
The Pi's are easily accessible in the container. I can frequently get to the container, the more difficult bit is getting them to you from there.

**Comment by PeterJCLaw** [comment]
This afternoon I've done a fresh deploy of https://github.com/PeterJCLaw/srcomp-kiosk/ onto my own Pi 2 using the latest Raspberry Pi OS Desktop (version from 2022-01-28, without recommended packages) and that worked fine (very lightweight testing by showing the "outside" page). I've done some small updates too, so we're now using Firefox's built-in `--kiosk` mode rather than the custom profile deploy mechanism we were using previously.

Most of this task is therefore still outstanding, though this gives confidence that the software we have should work fine despite several years without actually being used.

**Comment by PeterJCLaw** [comment]
I've just been through https://github.com/PeterJCLaw/srcomp-kiosk/ to update (and extend) its documentation so that hopefully it's now a bit more approachable to others.

**Comment by sedders123** [comment]
I have collected the box of Pis from Jake (https://github.com/srobo/inventory/commit/c39448020013b32c63dd68c48c91a6e755ae3bae) so can look at getting these set up

**Comment by PeterJCLaw** [comment]
@sedders123 can we call this done? Now that https://github.com/PeterJCLaw/srcomp-kiosk/pull/11 and https://github.com/PeterJCLaw/srcomp-kiosk/pull/16 are merged I think the prep aspect here is done?

**Comment by sedders123** [comment]
These are deployed in the venue now
