### ISSUE TITLE
Organise tickets for SR2022

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#749]
We need to organise the issuing of tickets for the competition.

### Original

[comp/media-consent/tickets](https://github.com/srobo/recurring-tasks/blob/master/comp/media-consent/tickets.yaml)

**Comment by trickeydan** [comment]
Now that we no longer have LDAP, do we need new software for this? (whether off-the-shelf or in-house)

**Comment by PeterJCLaw** [comment]
I believe the current plan is to not do tickets at all (and maybe do media consent on the door). Not sure if that's confirmed yet though and likely details need working out.

Regarding off-the-shelf stuff -- I had a look in #286 and the core issue is that what we think of as tickets aren't really tickets. Most ticket systems assume that you're going to be selling the tickets in some fashion (even if the price is zero), which is inherently not what we're doing. For us tickets are a marker that someone has submitted a media consent form and so are issued much closer to invites than tickets.

On that task I also explored what a replacement in-house tool might look like (and I suspect that building something would be easy enough), but if we can do away with the whole thing that's likely even better.

**Comment by trickeydan** [comment]
> On that task I also explored what a replacement in-house tool might look like (and I suspect that building something would be easy enough), but if we can do away with the whole thing that's likely even better.

If we end up needing something, it would be good to know sooner rather than later. This would be a nice self-contained project to give to some new volunteers that would like a software project.

**Comment by Scarzy** [comment]
One idea that me and Alistair discussed was using the tickets on the door
to print a pre-filled in media consent form that then just needs signing.
This could then also have space for a sticker that is peeled off and put
onto a name badge on the end of the lanyards.

It should then hopefully speed up moving people in rather than them having
to fill it out completely on the door.

**Comment by PeterJCLaw** [comment]
> One idea that me and Alistair discussed was using the tickets on the door to print a pre-filled in media consent form that then just needs signing. This could then also have space for a sticker that is peeled off and put onto a name badge on the end of the lanyards.
>
> It should then hopefully speed up moving people in rather than them having to fill it out completely on the door.

This is an interesting idea, however:
- we'd need to pre-collect all the teams' details
- I fear printing speed would be a substantial bottleneck to entry

IMO if we're going to bother collecting individuals details we might as well have them print off the forms themselves and either submit them in advance (i.e: what we've done historically) or bring them pre-signed. The latter allows a route where we don't actually need to pre-collect user's data -- they could just submit it and get a personalised PDF back (without us storing the data at all).

However it's not clear to me that having the personal details on the form be typeset rather than hand-written is an advantage. In that regard, letting users download a blank form to fill & sign in at home and then bring along feels like the easiest path here. (We can still have blanks on the door for those who forget them/can't print them at home). This approach removes most of the on-the-door bottleneck by rewarding people who've done as we asked ahead of time with faster entry.

I think it'd be fine to let people have a blank slot in the lanyard insert (though perhaps still with their team on it) on which they can write their name. This greatly reduces the search space for the "right" lanyard too -- down from O(competitors) to O(teams).

**Comment by Scarzy** [comment]
>   This greatly reduces the search space for the "right" lanyard too --
> down from O(competitors) to O(teams).
>
I think you've missed what I meant regarding the stickers. All of the
lanyards would be blanks, and the sticker is on the media consent form, the
printing process not only populates the top part of the media consent form
that we then keep, but also populates the label with name and school. Then
we just peel off the sticker and apply it to the blank lanyard. There
shouldn't be any searching for the "right" lanyard at all.

In that regard, letting users download a blank form to fill & sign in at
> home and then bring along feels like the easiest path here. (We can still
> have blanks on the door for those who forget them/can't print them at
> home). This approach removes most of the on-the-door bottleneck by
> rewarding people who've done as we asked ahead of time with faster entry.
>
Marginally, as we would still need to check each form on arrival. Also, it
only takes 1 member of any given team to have forgotten it and the whole
team is stuck waiting as the responsible adult can't split themselves into
2, so the reward you hint at is likely practically non-existent.

**Comment by TomWheal** [comment]
Do we need a physically signed form? Can we collect agreements digitally via an online form?

**Comment by Scarzy** [comment]
Technically; yes I believe we can have them signed digitally online ahead
of time. So long as we have a way of being fairly confident that the person
who completed the form is indeed the person they claim to be.

Practically; they still have to be mapped to individuals on the door, some
of whom won't have done it in advance (either due to forgetting, or they
were just wandering past and decided to come in and take a look), and in
such a manner that e.g. an internet outage doesn't stop the entire process
of letting people in. It is probably far easier to just require everyone
passing through the door to hand over a signed bit of paper.

**Comment by PeterJCLaw** [comment]
Circling this back to a concrete proposal, I think the requirements we have are:
- attendees need to have signed a form and be able to demonstrate that to be given a lanyard & let in (unless they're withholding consent)
- the on the door process needs to work in the event of an internet outage
- validation of that on the door needs to be quick enough to not become a substantial bottleneck
- ideally validation on the door should be able to operate in parallel (assuming we have several reception desks)

This suggests we should minimise the on-the-door processing as much as possible, with the ideal case being that individuals just hand over a media consent form (or non-fungible token of one [^1]) in exchange for a lanyard [^2].

In my opinion this precludes the majority case involving either individuals or printers populating the forms on the door. Yes we need to account for this case, but it shouldn't be the majority.

A question we then need to address is whether we're happy with lanyard inserts that aren't pre-populated (at least not with more detail than institution names). Given the ease with which they can be passed between people I don't see why we wouldn't be.

Concretely then I propose:
- we put an unpopulated template on the website
   - if it can be an editable PDF users can partially fill out digitally that's all the better
- tell teams to populate the details themselves, print it, sign it and bring it along (I think it's highly likely that all teams have access to a printer _somewhere_)
- we ask team supervisors how many competitors they expect to bring
- we pre-print lanyard inserts with TLAs, Institution names and a space for a person's name (including some buffer on top of what the supervisor says, maybe `max(N+7, 10)` per team)
- on the door they hand it over to the reception staff, who copy their name on a suitable lanyard and then hand over the lanyard (this should ensure legibility of the lanyard and of the form)

In addition:
- we have a stack of pre-printed unpopulated forms on the door, for those who need to fill them in; once the person has done so they fit into the above flow
- individuals who are withholding consent say so at the desk and get a named lanyard of the other colour/however we're marking that

An assumption here is that individuals are approaching the reception desk one at a time, rather than a team at a time. If this is not the case then the reception staff writing the names will _appear_ to be a bottleneck. Depending on how much we care about the legibility/presence/accuracy of the names that aspect could be changed to allow the attendee to write the name.

This feels like it's a good balance of speed on the door and low effort to implement, while allowing for all the cases we're aware of. Teams who fully or mostly pre-complete the forms still get in the venue faster than those who don't, so there's incentive for the supervisors to get that sorted.

Thoughts?

[^1]: Yes, NFTs are _so hot right now_, but this is honestly the most correct terminology for what we want (and actually the role that "tickets" played in the past - once again SR was well ahead of the curve!)

[^2]: Ironically lanyards are actually fungible so one wonders whether that undermines things at all... (the wristbands were not, at least not without removal of body parts)

**Comment by prophile** [comment]
I endorse this plan

**Comment by WillB97** [comment]
I think it's a suitable plan sans having reception write names on lanyards. We can offer own-brand sharpies for teams to write on their lanyards at their pits to avoid crowding at reception.

**Comment by PeterJCLaw** [comment]
Yup, happy to drop that part if we're concerned about a bottleneck. The reception volunteers need to be clear that they must check the legibility of the forms _before_ handling over the lanyards though.

**Comment by PeterJCLaw** [comment]
@Scarzy we think we're happy to run with https://github.com/srobo/tasks/issues/750#issuecomment-1034198031, are you happy that that covers our (legal) obligations sufficiently?

**Comment by Scarzy** [comment]
I think in terms of process this is probably ok.

My concerns are more do we want competitor names and schools visible in pictures that we then broadcast publicly? This feels like a potential GDPR issue.

I'd be more tempted to drop the names completely and just show the TLA, maybe the school name (or "visitor" for visitors). This removes the delay at reception, and the need for pens in pits. I don't believe this would create any more of concern around people swapping lanyards as they could move the name labels between lanyards anyway.

**Comment by PeterJCLaw** [comment]
> My concerns are more do we want competitor names and schools visible in pictures that we then broadcast publicly? This feels like a potential GDPR issue.

Are the photos we put on the website really going to be high enough quality that this is a concern?

**Comment by RealOrangeOne** [comment]
We're happy that we no longer need tickets, so this issue can be closed.
