### ISSUE TITLE
Design wristbands for SR2022

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#751]
We need to design some wristbands for the competition.

### Original

[comp/wristbands/design](https://github.com/srobo/recurring-tasks/blob/master/comp/wristbands/design.yaml)

**Comment by sedders123** [comment]
If we're doing lanyards we may not need to design them? Just simple colour? Maybe some branding would still be nice though

**Comment by RealOrangeOne** [comment]
"design" I suspect would encompass colour, and also any potential thing on the end of them.

There was talk about putting the team name on the end, and printing it on entry.

**Comment by sedders123** [comment]
This has been designed

![Wristband 5](https://user-images.githubusercontent.com/1496834/160011936-549a0150-5979-4b73-aa3d-234c90abfd71.png)

**Comment by PeterJCLaw** [comment]
Just to check -- does that design definitely leave enough spaces in the right places for things? I had thought in the past that the design previously was a much wider aspect ratio -- closer to a thin strip than that is.

**Comment by sedders123** [comment]
The site we ordered these on had an online previewer which handled adding padding on either end, we're leaving the order task open until they have arrived and we're sure we're happy with them.

Also just as a note as I realise its not made its way to this task, we've gone with paper based wristbands (as opposed to fabric) this year due to budgetary constraints.
