### ISSUE TITLE
Kit handback arrangement

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#759]
Arrangements must be made for the kit handback procedure at the end of the competition.

### Original

[comp/kit-handback](https://github.com/srobo/recurring-tasks/blob/master/comp/kit-handback.yaml)

### Dependencies

 * #758 Plan how we will do extended kit loans to teams

**Comment by PeterJCLaw** [comment]
It should be noted, per https://github.com/srobo/tasks/issues/758#issuecomment-1027237991, that there aren't any post-competition kit loans, so we'll need to include that in the communications to teams that go with this organising.

**Comment by PeterJCLaw** [comment]
Currently the day schedules allow 15 minutes for kit return. Is that definitely going to be enough?

Quoting my comment from https://github.com/srobo/website/pull/395#discussion_r840377906:

> On Sunday evening people may have quite a way to travel. If we're advertising an End time then they'll likely assume that's a time they can actually be leaving at, so us having a bottleneck at the exit which makes that time less realistic doesn't seem fair.
> 
> Back to my original question: is 15 minutes enough time for Kit Return?
> 
> I don't know what's involved in the return, however often it involves someone looking in their kit to ensure that everything is actually present. This takes a while per team (certainly > 2 minutes) and while it can parallelise very well desk space quickly becomes the limiting factor.
> 
> To this end, many teams often start deconstructing their robots as soon as they're knocked out of the knockouts, in part so they can get away quickly at the end of the day. We typically therefore want to have kit return actually available throughout the afternoon to facilitate this (even if we don't actually advertise it).
> 
> Has this all been considered in the allowance of only 15 minutes for Kit Return?

**Comment by trickeydan** [comment]
> Currently the day schedules allow 15 minutes for kit return. Is that definitely going to be enough?

I doubt it. If you have any ideas on how we can speed up the process, I'm interested.

**Comment by WillB97** [comment]
From what I understand, this process should just involve verifying the RUB contains:
- Odroid
- Power board
- 2x Motor board
- Ruggeduino + screw shields
- Servo board
- 2x USB hub
- USB WiFi adapter
- USB stick
- 3x USB A-B cables
- 5x micro USB cables
- Camcons
- Webcam
- Odroid power cable
- Battery
- Slotted screwdriver

Probably using a printed ticklist that can be put in the RUB and then separating the battery so that they can be put in lipo bags once we have all the batteries back.

We don't need to inventory individual items at this stage, which would be a considerable bottleneck, since we know which RUB went to which team and the ticklist tells us what was present when we got it back. When everything is inventoried at kit collation this is a much more efficient process and we still have sufficient information to track missing parts.

**Comment by PeterJCLaw** [comment]
I thiiink in the past we may even have just done kit return as accepting back the box without checking the contents, on the same idea that we can check at kit collation which parts are where. Obviously that carries some risk of parts going missing and it taking a while for us to chase the teams, however as long as we seal the boxes at the competition (and don't open them until collation) there wouldn't be any loss of information. Not sure if I like the risk of part loss here, though I think this approach has been used in the past.

If we are going to check the parts on the day, definitely :+1: to having a printed checklist of parts to expect. Agree that in this case inventorying immediately adds very little value.
We'd need to think about how to check batteries at this stage -- since those definitely won't match up with the inventory. Also maybe any swapped out kit parts where we've issued spares. If we're always only issuing spares/batteries on a one-for-one basis then that simplifies things, though actually ensuring that that happens is its own challenge.

If we have the capacity, it might be worth doing some test runs of checking kit boxes -- to get a feel for how long that takes. That could then guide the time slot we need and the number of desks we need (to parallelise).

In terms of taking less time, the immediate thoughts I have are:
- parallelise as much as possible (obviously) -- if we can have 8 desks handling this then 15 minutes starts to look more reasonable (30 teams/8 desks == 4ish teams per desk)
- maybe ask teams to present their RUBs with the lids off, perhaps even ask that they tidy the wires somehow so it's easy to see what's in it? Not sure how viable this is
- allow kit return much earlier in the day -- if we assume that teams will start deconstructing their robots as soon as they're knocked out (which I suspect some will) then having kit return available (even if not on the schedule) from, say, 3-4pm (i.e: most of the knockouts but perhaps not the actual final match) this will allow teams who want to get away promptly with the opportunity to do so

A more radical option might be to have the teams return their kit in parts -- each part to its own desk, which ticks off from a list of teams. If we're looking at, say, 8 desks anyway this might actually work more efficiently as the return of any individual kit can now be parallelised and I'd expect the check of "is this the part I'm collecting, what's your TLA, write down TLA" to be faster than matching up the parts within a RUB against a checklist.
This approach hasn't been used before and probably has its own drawbacks, but throwing it out there as a potential idea.

Another very different option (and needing much more preparatory work) might be to have a web-page/app/something which can scan barcodes, look them up in the inventory to work out what part they are and then check them off interactively. This would ideally be able to do this from a video stream rather than a single-scan-reader so that you just point the camera at the kit and it figures it all out. _If_ this can be made to work it feels like it would be very quick for at least some of the components in the box. Coupling this approach with a request that teams place things in their box with the barcodes showing could be very fast in the happy path. The unhappy path shouldn't be any slower than the manual checklist approach (depending how much time is spent trying to make the tech recognise the thing the human can see in the image of course).
I don't think this one is a runner for this year, just due to the amount of software we'd need to create, but might be something to work towards for the future.

**Comment by WillB97** [comment]
> I thiiink in the past we may even have just done kit return as accepting back the box without checking the contents, on the same idea that we can check at kit collation which parts are where. 

If we haven't been checking the contents of kits what is taking the time? It doesn't take multiple minutes to take a box and put it in a pile.

> We'd need to think about how to check batteries at this stage -- since those definitely won't match up with the inventory. Also maybe any swapped out kit parts where we've issued spares. 

We don't actually care which battery comes back with which team, we only care the right quantity of batteries are coming back. 

> * parallelise as much as possible (obviously) -- if we can have 8 desks handling this then 15 minutes starts to look more reasonable (30 teams/8 desks == 4ish teams per desk)

This process does not seem like it should be taking that long. Increasing this from 4 to 8 volunteers seems like an inefficient use of volunteer time. We should focus on why we currently need several minutes per team.

> * maybe ask teams to present their RUBs with the lids off, perhaps even ask that they tidy the wires somehow so it's easy to see what's in it? Not sure how viable this is

The lids make little difference, we can always ask teams to clear out the extra wires especially if we provide a bin for it. This is more a convenience than a massive improvement.

> * allow kit return much earlier in the day -- if we assume that teams will start deconstructing their robots as soon as they're knocked out (which I suspect some will) then having kit return available ...

We have already been discussing doing this from 3pm to account for teams leaving after being knocked out. Since we don't know how many teams will take this option we can't accurately account for this when deciding the resources needed for the main handback.

> A more radical option might be to have the teams return their kit in parts -- each part to its own desk, which ticks off from a list of teams. If we're looking at, say, 8 desks anyway this might actually work more efficiently as the return of any individual kit can now be parallelised and I'd expect the check of "is this the part I'm collecting, what's your TLA, write down TLA" to be faster than matching up the parts within a RUB against a checklist. This approach hasn't been used before and probably has its own drawbacks, but throwing it out there as a potential idea.

My initial thoughts are:
- The current approach is also parallelised
- This adds the overhead of every team having to move between all 8 tables
- We end up having to capture TLA 8 times

**Comment by PeterJCLaw** [comment]
> > I thiiink in the past we may even have just done kit return as accepting back the box without checking the contents, on the same idea that we can check at kit collation which parts are where.
> 
> If we haven't been checking the contents of kits what is taking the time? It doesn't take multiple minutes to take a box and put it in a pile.

We've done several things in the past, with varying degrees of time taken and risk. If we are doing anything more than blindly accepting back a RUB then the additional time comes in two forms:
1. doing the check of the contents of the RUB
2. handling the case of something being missing

The main thing I'd comment is that this sort of activity tends to take longer than might be expected.

I don't know what's planned for this year, so I don't really know how long it's going to take.
My concern was that 15 minutes feels like it's a short amount of time to process all the teams in. Naively that's ~30s per team which really isn't a lot of time, hence asking the question.

I'm quite happy for those planning the kit return to determine the time needed and if that's less than the time available then that's fine!

> > We'd need to think about how to check batteries at this stage -- since those definitely won't match up with the inventory. Also maybe any swapped out kit parts where we've issued spares.
> 
> We don't actually care which battery comes back with which team, we only care the right quantity of batteries are coming back.

Indeed. It's the ensuring that the right number come back which is the hard part. There are plenty of ways that teams could accidentally end up with more than one battery at this point (or of any other kit component if they've been issued a spare).

**Comment by Scarzy** [comment]
Ok, so I might now be putting this in 2 places as I didn't realise this conversation was happening here, not on #743.

My thoughts, I don't know if any of these have already been considered off thread;
An extra volunteer on helpdesk to handle kit returns from when the knockouts start might alleviate a lot of the need at the end.
Do we have enough volunteers to near the end flood the pits and do kit return at the teams own desks? We won't be needing roving helpers, shepherds, or badgers at that point, and won't need any extra desks.

**Comment by PeterJCLaw** [comment]
Discussion from Doing this evening: 

- we're going to use a single form for spares issued and for kit return
- the form will capture the number of each type of item we expected and actually received from each team (e.g: 2 motor boards)
- the form will also capture any parts above the standard kit issue (e.g: from previous years) that we expected and actually received from each team
- the form will have the team's TLA and the part code of the RUB they have (the latter for double checking that the team in front of the checkers is the right one)
- we'll have a "Router" person in front of kit return who will hand out the kit return form to a team just before they approach an empty return desk (we have 4 desks & volunteers allocated)
- kit return desks will check that the right numbers of components are in the kit; mark this in pencil

If there are the right number of components:
- put the kit return form in the RUB
- close & seal the RUB with tape
  - TODO: work out which specific tape to use
- TODO: have the supervisor sign something?

If there are not the right number of components:
- keep the kit return form, give it back to the "Router"
- send the team to find the missing parts

If there are not the right number of components and the team are unable to find the remaining pieces:
- TODO

I hope that's everything we covered. I've added some TODOs which occurred to me while writing this up.
@trickeydan can we leave this with you to finalise? (happy to help with that if I can)
cc @Adimote @WillB97 in case there's anything I missed.

**Comment by trickeydan** [comment]
Kit Return has been done.
