### ISSUE TITLE
Show the live stream within the venue

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#875]
We should ensure the live stream of the competition is viewable within the venue. This enables everyone to see matches without actually being arena-side.
In the past the display has included a split-screen view of all the arenas which most people liked. It would be good to do this again.

### Original

[comp/livestream/local](https://github.com/srobo/recurring-tasks/blob/master/comp/livestream/local.yaml)

### Dependencies

 * #790 Arrange a live stream from the competition

**Comment by Tyler-Ward** [comment]
The info text on this is slightly out of date but in 2019 we used raspbery pis attached to the various monitors to display the stream from YouTube which worked fairly well.

in order to progress this ticket we will need to do the following
- [ ] Decide which screens are showing the livestream and which showing the comp info screens and arrange corresponding hardware #900
- [ ] Create/find a software image for any SR controlled machines driving the screens.

**Comment by PeterJCLaw** [comment]
I suspect that SR's pis (1As) are beefy enough to show the livestream.

ODROIDs might be an option though.

**Comment by PeterJCLaw** [comment]
We know which displays are showing the livestream (see https://github.com/srobo/tasks/issues/900). These will be set up as part of the general displays (https://github.com/srobo/tasks/issues/811).
