### ISSUE TITLE
Have a competition retrospective 

### ISSUE THREAD

**Issue by Adimote** [srobo/tasks#918]
We should have a retrospective meeting to identify what we can do better next year

**Comment by WillB97** [comment]
I believe the current proposal was to do this at Wednesday's meeting (27th) while things are still fresh in people's minds.

If this is the case we should advertise this soon so people turn up.

**Comment by PeterJCLaw** [comment]
![Huge Fan](https://user-images.githubusercontent.com/336212/165165618-94ef774c-ea9e-4411-b5a2-ad8a295007d2.png)

Big :+1: on having a retro.

I think we should be careful with how we run this, as we're likely to get a lot of different kinds of feedback and it could easily consume a lot of people's time uneconomically if everyone is discussing everything all in one go.

To that end I suggest that we clarify the brief well ahead of time and nominate someone to run it such that we maximise the value from the time available.

Without wanting to step on that person's toes, I'd also encourage considering having several separate reviews to facilitate more focussed discussion. That might mean breaking into groups to come up with reflections, or it might mean follow-on sessions to work on solutions -- I'm not sure what's best here. Broadly though I'd discourage a format where more than, say, 10 people, are trying to have a meeting all at once as that feels likely to end up being relatively low quality time for most.

In terms of clarifying the brief, I think we should pin down:
- Is this to cover the event or the year as a whole?
- Is setup/planning included? (If so, how far back are we going?)
- Is it expected to cover contributions from outside the Competition Team? (If so, how do we ensure that those people are involved too?)
- Are we expecting to spend time coming up with solutions? (If not, when/how are we going to do that?) (IMO deferring solutions out of the retro is better, but that may be a decision for the organiser)

Things for the organiser to think about:
- Are we having a single session for all volunteers?
- If so, how to ensure that everyone has a voice and feels heard, while keeping the session valuable for attendees given the likely wildly varying levels of contribution?
- Are we expecting to spend time coming up with solutions? (Also mentioned in the brief, see above)
- How to ensure that the retro is a space where everyone feels they can candidly share things? (search keyword: psychological safety)
- What format of outcome/output do we want? (Note that there are often trade-offs between candour in the meeting and detail of output)

Likely there's more to clarify/think about here -- please do add thoughts on the above. Note however that if we want this to happen this Wednesday we'll need to move fast on a lot of these, which may be challenging to do well.

**Comment by WillB97** [comment]
> To that end I suggest that we clarify the brief well ahead of time and nominate someone to run it such that we maximise the value from the time available.
> 
> Without wanting to step on that person's toes, I'd also encourage considering having several separate reviews to facilitate more focussed discussion. That might mean breaking into groups to come up with reflections, or it might mean follow-on sessions to work on solutions -- I'm not sure what's best here. Broadly though I'd discourage a format where more than, say, 10 people, are trying to have a meeting all at once as that feels likely to end up being relatively low quality time for most.

The issue is, I for one have points I'd like to discuss in several areas. So if we do these groups in parallel I would be unable to contribute to all of my points.

Equally, (and an issue that occurred in setup)  when things are only discussed in insular groups the people who have industry knowledge in the problem area are not involved which has lead to greatly overly convoluted or even totally wrong conclusions being reached.

To make use of time efficiently we need to split the retro into groups of related points and groups that are taking a long time to discuss should be converted into agenda points for the next meeting. We should also be using this first session to make sure the points are clear enough that we can all understand what the issue being raised is while people can remember what they originally made the point about.

> In terms of clarifying the brief, I think we should pin down:
> - Is this to cover the event or the year as a whole?
> - Is setup/planning included? (If so, how far back are we going?)
> - Is it expected to cover contributions from outside the Competition Team? (If so, how do we ensure that those people are involved too?)

This should be focused on the competition event alone. While this should include prep for the event, this should only be at a high level. If we feel that we need to discuss prep in more detail we can have a separate discussion later.

Since the event itself is a combined effort of all the teams there will be points that extend beyond the competition team. The best way to get their contribution is to have them at the meeting.

> - Are we expecting to spend time coming up with solutions? (If not, when/how are we going to do that?) (IMO deferring solutions out of the retro is better, but that may be a decision for the organiser)

We should be prioritising coming up with a concise list of the shortcomings of the event so that the future competition team can determine solutions. Where clear solutions are already known these can be noted down but we shouldn't be dwelling on these long.

**Comment by Tyler-Ward** [comment]
For info the notes are being collated at https://docs.google.com/document/d/1IgeMqTCY0nsQdtQkFb0aOZg739KH0T8aUtaARxSF1ac/edit#

**Comment by PeterJCLaw** [comment]
Retrospectives happened.
